---
spring:
  application.name: com.example.BuildingTracker

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server.error.include-message: always

location-api:
  url: "https://api.geoapify.com/v1/geocode/search?text="
  api-param: "&apiKey="
  api-key: ${LOCATION_API_KEY}